name: riderapp
description: Rider Connect App - Hybrid Mobile and Web Simulator.
version: 4.2.1+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.15.0
  geolocator: ^14.0.3
  flutter_local_notifications: ^22.0.1
  google_maps_flutter: ^2.17.1
  audioplayers: ^6.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/rider_profile.png
    - assets/images/customer_avatar.png
    - assets/images/delivery_proof.png
    - assets/sounds/new_order_alert.ogg
